// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "API del Clima de los planetas de Star Wars",
    "version": "1"
  },
  "paths": {
    "/fusionados": {
      "get": {
        "summary": "Obtener clima de un planeta aleatorio de Star Wars",
        "description": "Devuelve información del clima para un planeta aleatorio de Star Wars junto con un país de la Tierra que coincida",
        "tags": [
          "Weather"
        ],
        "operationId": "combined.get./fusionados",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response",
            "schema": {
              "$ref": "#/definitions/PlanetResponse"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/historial": {
      "get": {
        "summary": "Obtener historial del clima",
        "description": "Devuelve el historial de registros del clima para los planetas de Star Wars",
        "tags": [
          "History"
        ],
        "operationId": "history.get./historial",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "header",
            "name": "Authorization",
            "required": true,
            "type": "string",
            "description": "Token de autenticación de Cognito (Bearer token)"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "schema": {
              "$ref": "#/definitions/HistoryResponse"
            }
          },
          "401": {
            "description": "Unauthorized",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/almacenar": {
      "post": {
        "summary": "Almacenar información del clima",
        "description": "Almacena cualquier objeto JSON válido en la base de datos",
        "tags": [
          "Storage"
        ],
        "operationId": "store.post./almacenar",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "header",
            "name": "Authorization",
            "required": true,
            "type": "string",
            "description": "Token de autenticación de Cognito (Bearer token)"
          }
        ],
        "responses": {
          "200": {
            "description": "Successfully stored",
            "schema": {
              "$ref": "#/definitions/StoreResponse"
            }
          },
          "400": {
            "description": "Bad request - Invalid JSON",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "401": {
            "description": "Unauthorized",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Measurement": {
      "properties": {
        "value": {
          "title": "Measurement.value",
          "type": "number"
        },
        "unit": {
          "title": "Measurement.unit",
          "type": "string"
        }
      },
      "required": [
        "value",
        "unit"
      ],
      "additionalProperties": false,
      "title": "Measurement",
      "type": "object"
    },
    "Weather": {
      "properties": {
        "description": {
          "title": "Weather.description",
          "type": "string"
        },
        "temperature": {
          "$ref": "#/definitions/Measurement",
          "title": "Weather.temperature"
        },
        "feelsLike": {
          "$ref": "#/definitions/Measurement",
          "title": "Weather.feelsLike"
        },
        "humidity": {
          "$ref": "#/definitions/Measurement",
          "title": "Weather.humidity"
        },
        "windSpeed": {
          "$ref": "#/definitions/Measurement",
          "title": "Weather.windSpeed"
        },
        "pressure": {
          "$ref": "#/definitions/Measurement",
          "title": "Weather.pressure"
        },
        "visibility": {
          "$ref": "#/definitions/Measurement",
          "title": "Weather.visibility"
        },
        "cloudCoverage": {
          "$ref": "#/definitions/Measurement",
          "title": "Weather.cloudCoverage"
        }
      },
      "required": [
        "description",
        "temperature",
        "feelsLike",
        "humidity",
        "windSpeed",
        "pressure",
        "visibility",
        "cloudCoverage"
      ],
      "additionalProperties": false,
      "title": "Weather",
      "type": "object"
    },
    "PlanetResponse": {
      "properties": {
        "planetId": {
          "title": "PlanetResponse.planetId",
          "type": "string"
        },
        "planetName": {
          "title": "PlanetResponse.planetName",
          "type": "string"
        },
        "climate": {
          "title": "PlanetResponse.climate",
          "type": "string"
        },
        "terrain": {
          "title": "PlanetResponse.terrain",
          "type": "string"
        },
        "population": {
          "title": "PlanetResponse.population",
          "type": "string"
        },
        "weather": {
          "$ref": "#/definitions/Weather",
          "title": "PlanetResponse.weather"
        }
      },
      "required": [
        "planetId",
        "planetName",
        "climate",
        "terrain",
        "population",
        "weather"
      ],
      "additionalProperties": false,
      "title": "PlanetResponse",
      "type": "object"
    },
    "HistoryResponse": {
      "properties": {
        "items": {
          "items": {
            "$ref": "#/definitions/PlanetResponse"
          },
          "title": "HistoryResponse.items",
          "type": "array"
        },
        "lastEvaluatedKey": {
          "title": "HistoryResponse.lastEvaluatedKey",
          "type": "string"
        }
      },
      "required": [
        "items",
        "lastEvaluatedKey"
      ],
      "additionalProperties": false,
      "title": "HistoryResponse",
      "type": "object"
    },
    "StoreResponse": {
      "properties": {
        "message": {
          "title": "StoreResponse.message",
          "type": "string"
        }
      },
      "required": [
        "message"
      ],
      "additionalProperties": false,
      "title": "StoreResponse",
      "type": "object"
    },
    "ErrorResponse": {
      "properties": {
        "message": {
          "title": "ErrorResponse.message",
          "type": "string"
        },
        "code": {
          "title": "ErrorResponse.code",
          "type": "string"
        }
      },
      "required": [
        "message",
        "code"
      ],
      "additionalProperties": false,
      "title": "ErrorResponse",
      "type": "object"
    }
  },
  "securityDefinitions": {},
  "basePath": "/dev",
  "schemes": [
    "https"
  ]
};