export const PLANETS_COUNT = 60;
export const AVAILABLE_COUNTRIES = [
  "Albania",
  "Algeria",
  "Argentina",
  "Australia",
  "Austria",
  "Bahrain",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Bulgaria",
  "Cameroon",
  "Canada",
  "Chile",
  "Congo",
  "Costa Rica",
  "Croatia",
  "Curacao and Sint Maarten",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Ecuador",
  "Egypt",
  "Estonia",
  "Eswatini",
  "Finland",
  "France",
  "Gabon",
  "Germany",
  "Ghana",
  "Greece",
  "Guinea",
  "Guyana",
  "Hong Kong China",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Ireland",
  "Israel",
  "Italy",
  "Ivory Coast",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kuwait",
  "Latvia",
  "Lesotho",
  "Libya",
  "Lithuania",
  "Luxembourg",
  "Macao China",
  "Madagascar",
  "Malawi",
  "Maldives",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Moldova",
  "Mongolia",
  "Mozambique",
  "Myanmar",
  "Netherlands",
  "New Zealand",
  "New Zealand",
  "Niger",
  "Nigeria",
  "North Macedonia",
  "Norway",
  "Paraguay",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Republic of Korea",
  "Romania",
  "Russia-EN",
  "Russia-RU",
  "Saudi Arabia",
  "Serbia",
  "Seychelles",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "South Africa",
  "Spain",
  "Sudan",
  "Sweden",
  "Switzerland",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Trinidad and Tobago",
  "Ukraine",
  "United Kingdom of Great Britain and Northern Ireland",
  "Uruguay",
  "United States",
  "USA",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

export const TEMPERATURE_UNIT = "C";
export const HUMIDITY_UNIT = "%";
export const WIND_SPEED_UNIT = "m/s";
export const PRESSURE_UNIT = "hPa";
export const CLOUD_COVERAGE_UNIT = "%";
export const VISIBILITY_UNIT = "m";
